server:
  port: 2024

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: resilience4j
                fallbackUri: forward:/departmentFallback
              
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: resilience4j
                fallbackUri: forward:/userFallback
                
  security:
    oauth2:
      client:
        client-id: ati-ms
        client-secret: ati-pass
        scope: openid,profile,email
        authorization-uri: http://192.168.0.79:9199/auth-api/oauth/authorize
        token-uri: http://192.168.0.79:9199/auth-api/oauth/token
      resource:
        token-info-uri: http://192.168.0.79:9199/auth-api/oauth/token

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
